### PR TITLE
Add support for navigate-to, prefetch-src, and require-sri-for

### PR DESCRIPTION
**Pull request by oreoshake**
Fixes https://github.com/twitter/secure_headers/issues/387
Fixes https://github.com/twitter/secure_headers/issues/388
Fixes https://github.com/twitter/secure_headers/issues/264

Time for my annual CSP tuneup. Browser support for these things is probably mostly there maybe? Either way, the library shouldn't limit the use of these things.

I considered adding in arbitrary directive support but then the question of validation came up.

### CODE REVIEW

**Comment by tzvipm** [comment]
@oreoshake @toao any news on what's holding this PR back?

**Comment by oreoshake** [comment]
IIRC I got master in a bad state where I made backwards incompatible changes...I'll have to clean that up at some point.

**Comment by OldGareBear** [comment]
Hi @oreoshake this PR is great, I'd love to take advantage of the SRI feature. Since it looks like CI is green on latest master, I'm wondering if a merge of `master->missing-directives` would put this in a mergeable state? If there's anything I can do to help (I know you mentioned backwards compatibility issues in master), I'd be happy to contribute!

**Comment by oreoshake** [comment]
Hi, sorry @OldGareBear I've been letting this slip. I really wish someone would fork the project and take over.

I'll commit to cleaning this up, doing a proper deprecate and release cycle, get this merged, release a new major revision, and archive this project. I'll have some time in the next week or two.

It's time to fork. `securerer_headers`?

**Comment by oreoshake** [comment]
@vcsjones has volunteered to fork and maintain ✨ 🎊 https://twitter.com/vcsjones/status/1092867704304922624

Now I'm even more motivated to get going!

**Comment by slavingia** [comment]
eta?

**Comment by oreoshake** [comment]
Just release 6.1.0!

**Pull request merged**
